services:
  enset-ebank-discovery-service:
    build: ./discovery-service
    container_name: enset-ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      # -f genere code d'etat d'echec de la requete
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  enset-ebank-config-service:
    build: ./config-service
    container_name: enset-ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY-SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
    healthcheck:
      # -f genere code d'etat d'echec de la requete
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-ebank-discovery-service:
        condition: service_healthy

  enset-ebank-customer-service:
    build: ./customer-service
    container_name: enset-ebank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY-SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
    healthcheck:
      # -f genere code d'etat d'echec de la requete
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-ebank-config-service:
        condition: service_healthy

  enset-ebank-account-service:
    build: ./account-service
    container_name: enset-ebank-account-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY-SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
    healthcheck:
      # -f genere code d'etat d'echec de la requete
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-ebank-customer-service:
        condition: service_healthy

  enset-ebank-gateway-service:
    build: ./gateway-service
    container_name: enset-ebank-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY-SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
    depends_on:
      enset-ebank-config-service:
        condition: service_healthy
